// <auto-generated />
using System;
using Maliev.CompensationService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maliev.CompensationService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CompensationDbContext))]
    [Migration("20251229062316_AddBenefitsTables")]
    partial class AddBenefitsTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maliev.CompensationService.Domain.Entities.Benefit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BenefitType")
                        .HasColumnType("integer")
                        .HasColumnName("benefit_type");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<decimal?>("EmployeeContribution")
                        .HasColumnType("numeric")
                        .HasColumnName("employee_contribution");

                    b.Property<decimal?>("EmployerContribution")
                        .HasColumnType("numeric")
                        .HasColumnName("employer_contribution");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("BenefitType")
                        .HasDatabaseName("idx_benefits_type");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_benefits_active")
                        .HasFilter("is_active = true");

                    b.ToTable("benefits", (string)null);
                });

            modelBuilder.Entity("Maliev.CompensationService.Domain.Entities.BenefitsEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BenefitId")
                        .HasColumnType("uuid")
                        .HasColumnName("benefit_id");

                    b.Property<string>("CoverageLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("coverage_level");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<decimal?>("EmployeeContribution")
                        .HasColumnType("numeric")
                        .HasColumnName("employee_contribution");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrollment_date");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("termination_date");

                    b.HasKey("Id");

                    b.HasIndex("BenefitId")
                        .HasDatabaseName("idx_benefits_enroll_benefit");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("idx_benefits_enroll_employee");

                    b.HasIndex("EmployeeId", "Status")
                        .HasDatabaseName("idx_benefits_enroll_status");

                    b.HasIndex("EmployeeId", "BenefitId", "Status")
                        .IsUnique()
                        .HasFilter("status = 0");

                    b.ToTable("benefits_enrollments", (string)null);
                });

            modelBuilder.Entity("Maliev.CompensationService.Domain.Entities.CompensationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<string>("BaseSalary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base_salary_encrypted");

                    b.Property<decimal?>("BonusPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("bonus_percentage");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("change_reason");

                    b.Property<decimal?>("CommissionRate")
                        .HasColumnType("numeric")
                        .HasColumnName("commission_rate");

                    b.Property<int>("CompensationType")
                        .HasColumnType("integer")
                        .HasColumnName("compensation_type");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("USD")
                        .HasColumnName("currency");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_current");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("idx_comp_records_employee");

                    b.HasIndex("EmployeeId", "IsCurrent")
                        .IsUnique()
                        .HasDatabaseName("idx_comp_records_current")
                        .HasFilter("is_current = true");

                    b.ToTable("compensation_records", (string)null);
                });

            modelBuilder.Entity("Maliev.CompensationService.Domain.Entities.Dependent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BenefitsEnrollmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("benefits_enrollment_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("NationalId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("national_id_encrypted");

                    b.Property<int>("Relationship")
                        .HasColumnType("integer")
                        .HasColumnName("relationship");

                    b.HasKey("Id");

                    b.HasIndex("BenefitsEnrollmentId")
                        .HasDatabaseName("idx_dependents_enrollment");

                    b.ToTable("dependents", (string)null);
                });

            modelBuilder.Entity("Maliev.CompensationService.Domain.Entities.SalaryHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ChangeAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("change_amount");

                    b.Property<decimal>("ChangePercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("change_percentage");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("change_type");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<Guid>("CompensationRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("compensation_record_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsHighIncrease")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_high_increase");

                    b.Property<string>("NewSalary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_salary_encrypted");

                    b.Property<string>("PreviousSalary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("previous_salary_encrypted");

                    b.HasKey("Id");

                    b.HasIndex("CompensationRecordId");

                    b.HasIndex("EmployeeId", "EffectiveDate")
                        .HasDatabaseName("idx_salary_hist_employee");

                    b.ToTable("salary_histories", (string)null);
                });

            modelBuilder.Entity("Maliev.CompensationService.Domain.Entities.BenefitsEnrollment", b =>
                {
                    b.HasOne("Maliev.CompensationService.Domain.Entities.Benefit", "Benefit")
                        .WithMany("Enrollments")
                        .HasForeignKey("BenefitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Benefit");
                });

            modelBuilder.Entity("Maliev.CompensationService.Domain.Entities.Dependent", b =>
                {
                    b.HasOne("Maliev.CompensationService.Domain.Entities.BenefitsEnrollment", "Enrollment")
                        .WithMany("Dependents")
                        .HasForeignKey("BenefitsEnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("Maliev.CompensationService.Domain.Entities.SalaryHistory", b =>
                {
                    b.HasOne("Maliev.CompensationService.Domain.Entities.CompensationRecord", "CompensationRecord")
                        .WithMany("SalaryHistories")
                        .HasForeignKey("CompensationRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompensationRecord");
                });

            modelBuilder.Entity("Maliev.CompensationService.Domain.Entities.Benefit", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Maliev.CompensationService.Domain.Entities.BenefitsEnrollment", b =>
                {
                    b.Navigation("Dependents");
                });

            modelBuilder.Entity("Maliev.CompensationService.Domain.Entities.CompensationRecord", b =>
                {
                    b.Navigation("SalaryHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
