// <auto-generated />
using System;
using Maliev.CompensationService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maliev.CompensationService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CompensationDbContext))]
    [Migration("20251229060207_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maliev.CompensationService.Domain.Entities.CompensationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<string>("BaseSalary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base_salary_encrypted");

                    b.Property<decimal?>("BonusPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("bonus_percentage");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("change_reason");

                    b.Property<decimal?>("CommissionRate")
                        .HasColumnType("numeric")
                        .HasColumnName("commission_rate");

                    b.Property<int>("CompensationType")
                        .HasColumnType("integer")
                        .HasColumnName("compensation_type");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("USD")
                        .HasColumnName("currency");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_current");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("idx_comp_records_employee");

                    b.HasIndex("EmployeeId", "IsCurrent")
                        .IsUnique()
                        .HasDatabaseName("idx_comp_records_current")
                        .HasFilter("is_current = true");

                    b.ToTable("compensation_records", (string)null);
                });

            modelBuilder.Entity("Maliev.CompensationService.Domain.Entities.SalaryHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ChangeAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ChangePercentage")
                        .HasColumnType("numeric");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompensationRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("NewSalary")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PreviousSalary")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CompensationRecordId");

                    b.ToTable("SalaryHistory");
                });

            modelBuilder.Entity("Maliev.CompensationService.Domain.Entities.SalaryHistory", b =>
                {
                    b.HasOne("Maliev.CompensationService.Domain.Entities.CompensationRecord", "CompensationRecord")
                        .WithMany("SalaryHistories")
                        .HasForeignKey("CompensationRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompensationRecord");
                });

            modelBuilder.Entity("Maliev.CompensationService.Domain.Entities.CompensationRecord", b =>
                {
                    b.Navigation("SalaryHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
